version: "3.8"
services:
  front_server:
    image: nginx:1.16.0
    container_name: maps_front_server
    volumes:
      - ./front_server/dependencies/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./front_server/dependencies/nginx-conf/conf.d:/etc/nginx/conf.d
      - ./front_server/public:/usr/share/nginx/html
    ports:
      - "7000:80"
  database:
    image: postgres:12.4
    container_name: maps_database
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/database
      - data-postgres12:/var/lib/postgresql/12/main
      - /dev/log:/dev/log
    ports:
      - "6432:5432"
  user_service:
    image: user_service
    build:
      context: user_service/dependencies/docker
      dockerfile: Dockerfile
    container_name: maps_user_service
    restart: always
    volumes:
      - ./user_service:/usr/user_service
    env_file:
      - ./user_service/.env

volumes:
  data-postgres12:
